language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
cache: pip
install:
  - pip install codecov
  - pip install -r requirements.txt

script:
  - python setup.py install
  - cd pypgatk
  - python tests/pypgatk_tests.py

after_success:
  - codecov
