language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
cache: pip
install:
  - pip install codecov
  - pip install pytest-cov pytest
  - pip install -r requirements.txt

script:
  - python setup.py install
  - python pypgatk/tests/pypgatk_tests.py
  - py.test  --cov-report term --cov=pypgatk/tests/

after_success:
  - codecov
