cosmic_data_downloader:
  output_directory: database_cosmic
  cosmic_server:
    cosmic_ftp: https://cancer.sanger.ac.uk
    mutations_url: cosmic/file_download/GRCh38/cosmic/v88
    mutations_file: CosmicMutantExport.tsv.gz
    cosmic_user: ""
    cosmic_password: ""
  logger:
    formatters:
      DEBUG: "%(asctime)s [%(levelname)7s][%(name)48s][%(module)32s, %(lineno)4s] %(message)s"
      INFO: "%(asctime)s [%(levelname)7s][%(name)48s] %(message)s"
    loglevel: DEBUG